export default {
    "page_title" : "ورود",
    "email" : "ایمیل",    
    "password" : "کلمه عبور",
    "forgot_password" : "بازیابی حساب کاربری",  
    "login" : "ورود",
    "validation_email_required" : "لطفا ایمیل را وارد نمایید.",
    "validation_email_email" : "ایمیل باید معتبر باشد.",
    "validation_password_required" : "لطفا کلمه عبور را وارد نمایید.",
    "login_failed" : "ایمیل یا کلمه عبور صحیح نمی باشد.",
    "login_account_disabled" : "حساب کاربری شما غیرفعال می باشد.",
    "login_account_blocked" : "حساب کاربری شما مسدود می باشد.",
    "no_access" : "برای دسترسی به پنل مدیریت باید ابتدا وارد شوید.",
    "login_success_logout" : "شما با موفقیت خارج شدید.",
    "profile" : "ویرایش پروفایل",
    "profile_first_name" : "نام",
    "profile_last_name" : "نام خانوادگی",
    "profile_email" : "ایمیل",
    "profile_pass1" : "کلمه عبور جاری",
    "profile_pass2" : "کلمه عبور جدید",
    "profile_pass3" : "تکرار کلمه عبور جدید",
    "profile_avatar" : "تصویر",
    "profile_validation_first_name" : "لطفا نام را وارد نمایید.",
    "profile_validation_last_name" : "لطفا نام خانوادگی را وارد نمایید.",
    "profile_save_success" : "با موفقیت ذخیره شد.",
    "profile_validation_email_empty" : "لطفا ایمیل را وارد نمایید.",
    "profile_validation_email_not_valid" : "ایمیل باید معتبر باشد.",
    "profile_save_error_email" : "ایمیل تکراری می باشد.",
    "profile_hint_password_change" : "اگر نمی خواهید کلمه عبور را تغییر دهید فیلد های زیر را خالی قرار دهید.",
    "profile_validation_pass2_is_empty" : "لطفا کلمه عبور جدید را وارد نمایید.",
    "profile_validation_pass3_is_empty" : "لطفا تکرار کلمه عبور جدید را وارد نمایید.",
    "profile_validation_pass3_is_not_match" : "تکرار کلمه عبور جدید یکسان نمی باشد.",
    "profile_save_error_current_password_is_not_correct" : "کلمه عبور جاری صحیح نمی باشد.",
    "profile_delete_avatar" : "حذف تصویر",
};